name: Build

on: 
  push:
    branch: main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          sudo xcode-select -s /Applications/Xcode_15.3.app
          xcodebuild -scheme PragueOAPISwiftUI -sdk "iphonesimulator"
  tests:
    name: Tests
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Tests
        run: |
          sudo xcode-select -s /Applications/Xcode_15.3.app
          xcrun simctl create "iPhone 13 Pro Max" "iPhone 13 Pro Max"
          xcodebuild test -scheme PragueOAPISwiftUI -destination "name=iPhone 13 Pro Max" -resultBundlePath "Tests.xcresult"
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: Tests.xcresult
          path: Tests.xcresult