name: Build

on: 
  [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild -scheme PragueOAPISwiftUI -sdk "iphonesimulator"